function [fitresult, gof] = createFit(temp, thermex)
%CREATEFIT(TEMP,THERMEX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : temp
%      Y Output: thermex
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Feb-2018 10:13:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( temp, thermex );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'thermex vs. temp', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel temp
ylabel thermex
grid on


