/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 25-Jun-2018 09:45:35
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\Matlab\R2017a\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
                  -0,-0.005878733079749,  0.01225497357087,   0.1012036621354,
     0.2360642383216,   0.3127117181038,   0.2360642383216,   0.1012036621354,
    0.01225497357087,-0.005878733079749,                -0
};
