/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 15-May-2018 16:41:00
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 21
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\Matlab\R2017a\extern\include\tmwtypes.h 
 */
const int BL = 21;
const real64_T B[21] = {
                   0, 0.001544211433724,  0.00681929406853,  0.01632506464091,
    0.02982457077583,  0.04631057250877,  0.06411817343756,  0.08116848617224,
    0.09530154584357,   0.1046378098432,   0.1079005425513,   0.1046378098432,
    0.09530154584357,  0.08116848617224,  0.06411817343756,  0.04631057250877,
    0.02982457077583,  0.01632506464091,  0.00681929406853, 0.001544211433724,
                   0
};
